import { ITemplateContext } from "../interfaces";

export const ID = 'id',
    TRANSLATE_3D_HIDDEN = 'translate3d(-1000px,-1000px,0)',
    ATTR_AREA_SELECTED = 'area-selected',
    POSITION = 'position',
    POSITION_ZERO = '0',
    ITEM_ID = 'item-id',
    KEY_SPACE = ' ',
    KEY_ARR_LEFT = 'ArrowLeft',
    KEY_ARR_UP = 'ArrowUp',
    KEY_ARR_RIGHT = 'ArrowRight',
    KEY_ARR_DOWN = 'ArrowDown',
    EVENT_FOCUS_IN = 'focusin',
    EVENT_FOCUS_OUT = 'focusout',
    EVENT_KEY_DOWN = 'keydown',
    CLASS_NAME_SNAPPED = 'snapped',
    CLASS_NAME_SNAPPED_OUT = 'snapped-out',
    CLASS_NAME_FOCUS = 'focus';

export const DEFAULT_TEMPLATE_CONTEXT: ITemplateContext = {
    data: undefined,
    prevData: undefined,
    nextData: undefined,
    measures: null,
    config: {
        focused: false,
        selected: false,
        collapsed: false,
        focus: function (): void { },
        select: function (selected: boolean | undefined): void { },
        collapse: function (collapsed: boolean | undefined): void { },
        new: false,
        odd: false,
        even: false,
        collapsable: false,
        sticky: 0,
        selectable: false,
        snap: false,
        snapped: false,
        snappedOut: false,
        isVertical: false,
        dynamic: false,
        isSnappingMethodAdvanced: false,
        tabIndex: 0,
        zIndex: '0',
    },
    reseted: false,
    index: -1,
};
