export const START_COLLECTION_PREFIX_ID = 'n',
    END_COLLECTION_PREFIX_ID = 'p',
    DEFAULT_BUFFER_EXTREMUM_THRESHOLD = 15,
    DEFAULT_MAX_BUFFER_SEQUENCE_LENGTH = 30,
    DEFAULT_RESET_BUFFER_SIZE_TIMEOUT = 10000,
    IS_NEW = 'n';;
